version: '3'

services:
  php_apache:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: cocotons
      MYSQL_DATABASE: cocotons
      MYSQL_USER: cocotons
      MYSQL_PASSWORD: cocotons
    ports:
      - "3306:3306"
    volumes:
      - ./docker/sql_init:/docker-entrypoint-initdb.d
      - ./docker/dbdata:/var/lib/mysql

